/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-secondary-fixed-variant': '#174a6c',
        'surface-container-lowest': '#ffffff',
        'surface-tint': '#166395',
        'on-primary-fixed-variant': '#004a75',
        primary: {
          DEFAULT: '#004268',
          container: '#005a8c',
          fixed: '#cde5ff',
          'fixed-dim': '#95ccff',
        },
        'on-primary': {
          DEFAULT: '#ffffff',
          container: '#9fd0ff',
          fixed: '#001d32',
        },
        'surface-dim': '#cfdaf1',
        'surface-container-high': '#dee8ff',
        'tertiary-container': '#525658',
        'inverse-on-surface': '#ebf1ff',
        'on-tertiary-fixed': '#181c1e',
        'on-surface-variant': '#41474f',
        'secondary-fixed': '#cce5ff',
        'secondary-container': '#aad7ff',
        'surface-bright': '#f9f9ff',
        'outline-variant': '#c1c7d0',
        secondary: {
          DEFAULT: '#346285',
          fixed: '#cce5ff',
          'fixed-dim': '#9ecbf3',
          container: '#aad7ff',
        },
        'on-secondary': {
          DEFAULT: '#ffffff',
          container: '#2f5e80',
          fixed: '#001e31',
        },
        'error-container': '#ffdad6',
        'on-primary-fixed': '#001d32',
        'inverse-primary': '#95ccff',
        background: '#f9f9ff',
        'surface-container-low': '#f0f3ff',
        'surface-container': '#e7eeff',
        error: '#ba1a1a',
        'on-surface': '#111c2c',
        'on-background': '#111c2c',
        tertiary: {
          DEFAULT: '#3b3f41',
          container: '#525658',
          fixed: '#e0e3e5',
          'fixed-dim': '#c4c7c9',
        },
        'on-tertiary': {
          DEFAULT: '#ffffff',
          container: '#c8cbcd',
        },
        'primary-fixed-dim': '#95ccff',
        'on-tertiary-fixed-variant': '#434749',
        'on-error': '#ffffff',
        surface: '#f9f9ff',
        'surface-variant': '#d8e3fa',
        'surface-container-highest': '#d8e3fa',
        'inverse-surface': '#263142',
        'tertiary-fixed': '#e0e3e5',
        'tertiary-fixed-dim': '#c4c7c9',
        'on-error-container': '#93000a',
        outline: '#717880',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        'stack-lg': '32px',
        'margin-mobile': '16px',
        'section-gap': '80px',
        'stack-sm': '8px',
        'stack-md': '16px',
        gutter: '24px',
        'container-max': '1280px',
      },
      fontFamily: {
        'body-md': ['Inter', 'sans-serif'],
        'headline-lg': ['Montserrat', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'headline-xl': ['Montserrat', 'sans-serif'],
        'headline-lg-mobile': ['Montserrat', 'sans-serif'],
        'headline-md': ['Montserrat', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        montserrat: ['Montserrat', 'sans-serif'],
        inter: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-xl': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};
